name: NDCore
version: '${project.version}'
main: dev.nelmin.ndcore.NDCore
api-version: '1.21'
authors: [ Nelmin ]
description: The Core of all Plugins by Nelmin
website: https://nelmin.dev/projects/minecraft/core
