name: Build & Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g. 1.0.0)'
        required: true
        type: string

concurrency:
  group: "build-release"
  cancel-in-progress: true

jobs:
  check_should_run:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ github.event_name == 'workflow_dispatch' || (contains(github.event.head_commit.message, 'release(') && endsWith(github.event.head_commit.message, ')')) }}
    steps:
      - run: echo "Checking if workflow should run"

  build:
    needs: check_should_run
    if: needs.check_should_run.outputs.should_run == 'true'
    runs-on: ubuntu-latest

    outputs:
      jar_hash: ${{ steps.hash_calculation.outputs.hash }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.13

      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 8.13

      - name: Build with Gradle
        run: ./gradlew clean shadowJar

      - name: Generate checksum
        run: |
          cd build/libs
          sha256sum NDCore-shaded.jar > NDCore-shaded.jar.sha25

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NDCore-${{ github.run_id }}
          path: |
            build/libs/NDCore-shaded.jar
            build/libs/NDCore-shaded.jar.sha256

  release:
    needs: [check_should_run, build]
    if: needs.check_should_run.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: NDCore-${{ github.run_id }}
          path: build/libs

      - name: Validate checksum
        run: |
          cd build/libs
          sha256sum -c NDCore-shaded.jar.sha256

      - name: Import GPG Key
        id: import_gpg
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" > private.asc
          gpg --batch --pinentry-mode loopback --passphrase "$PASSPHRASE" --import private.asc
          echo "fingerprint=$(gpg --fingerprint --with-colons ${{ secrets.GPG_KEY_ID }} | awk -F: '$1 == "fpr" {print $10;exit}')" >> $GITHUB_OUTPUT
          rm private.asc

      - name: Sign JAR
        run: |
          gpg --batch --pinentry-mode loopback \
              --passphrase "${{ secrets.GPG_PASSPHRASE }}" \
              --detach-sign --armor \
              --local-user ${{ secrets.GPG_KEY_ID }} \
              --output build/libs/NDCore-shaded.jar.asc \
              build/libs/NDCore-shaded.jar

          gpg --verify build/libs/NDCore-shaded.jar.asc build/libs/NDCore-shaded.jar

      - name: Prepare Release Assets
        run: |
          mkdir -p release_files
          cp public-gpg-key.asc release_files/
          cp build/libs/NDCore.* release_files/

      - name: Extract Version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            # Get version from gradle.properties
            VERSION=$(grep "project.version" gradle.properties | cut -d'=' -f2)
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Prepare Release Notes
        run: cat "descriptions/${{ steps.version.outputs.version }}.txt" > release_notes.md

      - name: Prepare release files
        run: |
          cd release_files
          mv NDCore-shaded.jar NDCore.jar
          sha256sum NDCore.jar > NDCore.jar.sha256    

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: 🎮 NDCore v${{ steps.version.outputs.version }}
          body_path: release_notes.md
          files: |
            release_files/NDCore.jar
            release_files/NDCore.jar.asc
            release_files/public-gpg-key.asc
          draft: false
          prerelease: false